# Generated by Django 5.2.12 on 2026-03-04 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('vertical', models.CharField(blank=True, choices=[('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('technology', 'Technology'), ('healthcare', 'Healthcare'), ('financial_services', 'Financial Services'), ('education', 'Education'), ('energy', 'Energy'), ('non_profit', 'Non-Profit'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('hq_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('general_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hq_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('customer', 'Customer'), ('inactive', 'Inactive')], default='prospect', max_length=50)),
                ('arr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outreach_history', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('email3', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('outreach_history', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='core.account')),
                ('contact_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('interest_shown', 'Interest Shown'), ('meeting_booked', 'Meeting Booked'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiating', 'Negotiating'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='prospecting', max_length=50)),
                ('arr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('inbound_cold', 'Inbound Cold'), ('inbound_warm', 'Inbound Warm'), ('outbound', 'Outbound'), ('referral', 'Referral'), ('event', 'Event'), ('other', 'Other')], max_length=50, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('outreach_history', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='core.account')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='core.contact')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
            ],
        ),
    ]
