# Generated by Django 5.2.12 on 2026-03-04 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='billing_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='employee_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='booth_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='booth_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='booth_size',
            field=models.CharField(blank=True, choices=[('none', 'No Booth'), ('table_top', 'Table Top'), ('10x10', '10x10'), ('10x20', '10x20'), ('20x20', '20x20'), ('20x30', '20x30'), ('20x40', '20x40'), ('custom', 'Custom')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='forecast_category',
            field=models.CharField(blank=True, choices=[('in_forecast', 'In Forecast'), ('out_of_forecast', 'Out of Forecast'), ('stretch', 'Stretch'), ('unlikely', 'Unlikely')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(blank=True, choices=[('vendor', 'Vendor'), ('food_vendor', 'Food Vendor'), ('guest_appearance', 'Guest Appearance'), ('panel', 'Panel'), ('photo_op', 'Photo Op'), ('signing', 'Signing'), ('activity_room', 'Activity Room'), ('custom_room', 'Custom Room'), ('sponsor', 'Sponsor'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='planning', max_length=50)),
                ('total_attendance_cap', models.IntegerField(blank=True, null=True)),
                ('vendor_capacity', models.IntegerField(blank=True, null=True)),
                ('food_vendor_capacity', models.IntegerField(blank=True, null=True)),
                ('guest_capacity', models.IntegerField(blank=True, null=True)),
                ('panel_room_capacity', models.IntegerField(blank=True, null=True)),
                ('photo_op_capacity', models.IntegerField(blank=True, null=True)),
                ('activity_room_capacity', models.IntegerField(blank=True, null=True)),
                ('signing_capacity', models.IntegerField(blank=True, null=True)),
                ('custom_room_1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_room_1_capacity', models.IntegerField(blank=True, null=True)),
                ('custom_room_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_room_2_capacity', models.IntegerField(blank=True, null=True)),
                ('custom_room_3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_room_3_capacity', models.IntegerField(blank=True, null=True)),
                ('custom_room_4_name', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_room_4_capacity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='core.event'),
        ),
    ]
